# Generated by Django 5.0.6 on 2024-07-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('Not classified', '1. Not classified'), ('Information', '2. Information'), ('Warning', '3. Warning'), ('Average', '4. Average'), ('High', '5. High'), ('Disaster', '6. Disaster')], max_length=16, null=True),
        ),
    ]
