# Generated by Django 5.0.6 on 2024-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_case_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('1. Not classified', '1. Not classified'), ('2. Information', '2. Information'), ('3. Warning', '3. Warning'), ('4. Average', '4. Average'), ('5. High', '5. High'), ('6. Disaster', '6. Disaster')], max_length=20, null=True),
        ),
    ]
