# Generated by Django 5.0.6 on 2024-06-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_case_caseclosed_alter_case_casecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseClosed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='caseCreated',
            field=models.CharField(max_length=8),
        ),
    ]
