# Generated by Django 5.0.6 on 2024-06-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_case_caseclosed_alter_case_casecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseClosed',
            field=models.CharField(default='no', max_length=8),
        ),
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[(1, 'Not classified'), (2, 'Information'), (3, 'Warning'), (4, 'Average'), (5, 'High'), (6, 'Disaster')], default='', max_length=2),
        ),
    ]
