# Generated by Django 5.0.6 on 2024-06-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_case_caseclosed_alter_case_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('caseId', 'description'), 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('caseId', 'description')},
        ),
    ]
