# Generated by Django 5.0.6 on 2024-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_case_options_alter_case_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseClosed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='caseCreated',
        ),
    ]
