# Generated by Django 5.0.6 on 2024-06-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_case_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='severity',
        ),
    ]
