# Generated by Django 5.0.6 on 2024-06-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_case_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('1', 'Not classified'), ('2', 'Information'), ('3', 'Warning'), ('4', 'Average'), ('5', 'High'), ('6', 'Disaster')], max_length=2, null=True),
        ),
    ]
