# Generated by Django 5.0.6 on 2024-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_case_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('1', '1. Not classified'), ('2', '2. Information'), ('3', '3. Warning'), ('4', '4. Average'), ('5', '5. High'), ('6', '6. Disaster')], max_length=2, null=True),
        ),
    ]
